"""Regenerate the mechanical half of context/MAP.md.

The hand-written half of the map -- what a feature is, why it exists -- is
worth writing once. The route table and the component graph are not: they go
stale the moment a file moves, and a stale map costs more than no map. So
they are derived from the source on demand, between the markers below.

    python scripts/build_map.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "context" / "MAP.md"
START = "<!-- generated:start -->"
END = "<!-- generated:end -->"

API_DIR = ROOT / "backend" / "app" / "api"
SRC = ROOT / "frontend" / "src"

PREFIX = re.compile(r'Blueprint\(\s*"[^"]+",\s*__name__,\s*url_prefix="([^"]*)"')
ROUTE = re.compile(r'^@bp\.(get|post|put|patch|delete)\("([^"]*)"\)', re.M)
HANDLER = re.compile(r"^def (\w+)", re.M)


def routes() -> list[str]:
    rows = []
    for path in sorted(API_DIR.glob("*.py")):
        if path.name == "__init__.py":
            continue
        text = path.read_text(encoding="utf-8")
        prefix = PREFIX.search(text)
        if not prefix:
            continue
        for match in ROUTE.finditer(text):
            verb, rule = match.group(1).upper(), match.group(2)
            handler = HANDLER.search(text, match.end())
            name = handler.group(1) if handler else "?"
            line = text.count("\n", 0, match.start()) + 1
            url = f"/api{prefix.group(1)}{rule}" or "/api"
            rows.append(f"| `{verb} {url}` | `{name}` | [`{path.relative_to(ROOT).as_posix()}:{line}`]"
                        f"(../{path.relative_to(ROOT).as_posix()}#L{line}) |")
    return rows


def module_name(path: Path) -> str:
    return path.name.rsplit(".", 1)[0]


def graph() -> list[str]:
    """Who imports each component, hook and lib module."""
    files = [p for p in SRC.rglob("*.ts*") if p.suffix in {".ts", ".tsx"}]
    bodies = {p: p.read_text(encoding="utf-8") for p in files}
    rows = []
    targets = sorted(
        [p for p in files if p.parent.name in {"components", "lib"}]
        + [p for p in files if p.parent.name == "hooks" and p.name != "index.ts"],
        key=lambda p: (p.parent.name, p.name),
    )
    for target in targets:
        name = module_name(target)
        needle = f"/{name}'"
        users = sorted(
            p.relative_to(SRC).as_posix()
            for p, body in bodies.items()
            if p != target and needle in body and p.name != "index.ts"
        )
        rows.append(f"| `{target.relative_to(SRC).as_posix()}` | {', '.join(f'`{u}`' for u in users) or '--'} |")
    return rows


def main() -> None:
    text = MAP.read_text(encoding="utf-8")
    block = [
        START,
        "",
        f"_Generated by `scripts/build_map.py`. Do not edit by hand._",
        "",
        "### Every API route",
        "",
        "| Route | Handler | Source |",
        "|---|---|---|",
        *routes(),
        "",
        "### Who imports what",
        "",
        "A component with no importers is either an entry point or dead code.",
        "",
        "| Module | Imported by |",
        "|---|---|",
        *graph(),
        "",
        END,
    ]
    head, _, rest = text.partition(START)
    _, _, tail = rest.partition(END)
    MAP.write_text(head + "\n".join(block) + tail, encoding="utf-8")
    print(f"wrote {MAP.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
